/**
 * Every tool name this project hands out or will hand out again.
 *
 * Both sides use this list: the module refuses a registration from another
 * module under one of these names, and the server drops a third-party tool
 * with such a name from its list. The previous module compared against its
 * internal query names (`listScenes`) instead of tool names (`list-scenes`),
 * so the protection only held on the server.
 *
 * The list covers names that are not implemented yet as well. A module that
 * registers `move-token` today would otherwise collide with the day that tool
 * returns.
 */
export const RESERVED_TOOL_NAMES: ReadonlySet<string> = new Set([
  // The 71 tools of the last release of the previous generation
  'actor-refresh-from-source',
  'actor-set-token',
  'assign-actor-ownership',
  'cancel-map-job',
  'check-map-status',
  'create-actor-from-compendium',
  'create-campaign-dashboard',
  'create-compendium',
  'create-quest-journal',
  'create-roll-table',
  'create-scene',
  'create-scene-note',
  'delete-compendium',
  'delete-compendium-entries',
  'delete-playlist',
  'delete-roll-table',
  'delete-scene',
  'dnd5e-add-feature',
  'dnd5e-add-features-from-compendium',
  'dnd5e-create-npc',
  'export-to-compendium',
  'folder-delete',
  'folder-rename',
  'generate-map',
  'get-character',
  'get-character-entity',
  'get-compendium-entry-full',
  'get-compendium-item',
  'get-current-scene',
  'get-permissions',
  'get-world-info',
  'import-from-compendium',
  'journal-add-page',
  'journal-append-page',
  'journal-create',
  'journal-delete',
  'journal-delete-page',
  'journal-link-tags',
  'journal-page-from-file',
  'journal-rename',
  'journal-rewrite-images',
  'journal-set-page',
  'journal-split-page',
  'link-quest-to-npc',
  'list-actor-ownership',
  'list-characters',
  'list-compendium-entries',
  'list-compendium-packs',
  'list-compendiums',
  'list-creatures-by-criteria',
  'list-journals',
  'list-playlists',
  'list-roll-tables',
  'list-scene-folders',
  'list-scenes',
  'manage-actors',
  'manage-world-items',
  'organize-compendium',
  'refresh-scene-thumb',
  'remove-actor-ownership',
  'restore-scene',
  'search-character-items',
  'search-compendium',
  'search-journals',
  'set-compendium-lock',
  'set-scene-playlist',
  'switch-scene',
  'update-quest-journal',
  'update-scene',
  'use-item',
  'world-rewrite-paths',
  // Earlier tools of the previous generation: tokens and dice, effects and playback, game systems, Mac setup
  'check-mac-setup-status',
  'control-playlist',
  'create-dsa5-character-from-archetype',
  'delete-tokens',
  'get-available-conditions',
  'get-mac-setup-progress',
  'get-token-details',
  'list-dsa5-archetypes',
  'manage-effects',
  'manage-playlists',
  'move-token',
  'replace-journal-page',
  'request-player-rolls',
  'run-mac-setup',
  'toggle-token-condition',
  'update-scene-music',
  'update-token',
  'wfrp4e-add-items',
  'wfrp4e-update-actor',
  // The image tools of this generation. Listed only with GEMINI_API_KEY, reserved always, so no
  // other module takes a name that turns up as soon as a key is set.
  'edit-map-image',
  'generate-battlemap',
  'generate-scene-image',
]);
