/**
 * The small part of the Foundry client API this module uses.
 *
 * Declared by hand instead of pulling in the community type package: that
 * package lags behind (a beta for v13 while the tables run v14), is large, and
 * would type the module against an API it does not run on. Only what is used
 * is declared, so a wrong assumption shows up here in one place.
 *
 * Areas do not edit this file. Each area may bring its own
 * src/module/areas/<id>/foundry.d.ts, a global script without import or
 * export, whose interfaces merge with the ones here.
 * The base document and collection types and the world collections are
 * declared here once, loosely, so no two areas declare the same property
 * of `game` with different types; an area narrows a document with its own
 * interface that extends FoundryDocument.
 */

/** Any document. An area narrows it with an interface of its own that extends this one. */
interface FoundryDocument {
  readonly id: string;
  readonly uuid: string;
  readonly documentName: string;
  readonly parent: FoundryDocument | null;
  name?: string;
  update(changes: Record<string, unknown>, options?: Record<string, unknown>): Promise<unknown>;
  delete(options?: Record<string, unknown>): Promise<unknown>;
  toObject(): Record<string, unknown>;
  getEmbeddedCollection(embeddedName: string): FoundryCollection<FoundryDocument>;
  createEmbeddedDocuments(
    embeddedName: string,
    data: Record<string, unknown>[],
    options?: Record<string, unknown>
  ): Promise<FoundryDocument[]>;
  updateEmbeddedDocuments(
    embeddedName: string,
    updates: Record<string, unknown>[],
    options?: Record<string, unknown>
  ): Promise<FoundryDocument[]>;
  deleteEmbeddedDocuments(
    embeddedName: string,
    ids: string[],
    options?: Record<string, unknown>
  ): Promise<FoundryDocument[]>;
}

/** Foundry's Collection: a map by id with a few helpers. */
interface FoundryCollection<T> extends ReadonlyMap<string, T> {
  readonly contents: T[];
  getName(name: string): T | undefined;
  find(predicate: (entry: T) => boolean): T | undefined;
  filter(predicate: (entry: T) => boolean): T[];
  map<U>(mapper: (entry: T) => U): U[];
  some(predicate: (entry: T) => boolean): boolean;
}

/**
 * Foundry 14: a level of a scene, embedded as `scene.levels`. Before 14 a
 * scene has no levels; code reads `levels` as possibly absent.
 */
interface FoundryLevel extends FoundryDocument {
  sort?: number;
  background?: {
    src?: string | null;
    tint?: string | number | null;
    color?: string | number | null;
  };
  foreground?: { src?: string | null };
  elevation?: { bottom?: number | null; top?: number | null };
}

/** A scene, loosely. Areas narrow it further with their own interface. */
interface FoundryScene extends FoundryDocument {
  active?: boolean;
  /** Absent before Foundry 14. */
  levels?: FoundryCollection<FoundryLevel>;
}

/** One row of a compendium index. Index rows carry `_id`, not `id`. */
interface FoundryCompendiumIndexEntry {
  _id: string;
  name?: string;
  type?: string;
  img?: string | null;
  [field: string]: unknown;
}

/** A compendium, loosely. Areas narrow it with an interface that extends this one. */
interface FoundryCompendium {
  /** The full id, "package.name". */
  readonly collection: string;
  readonly documentName: string;
  readonly title: string;
  readonly locked: boolean;
  readonly metadata: {
    id?: string;
    name: string;
    label: string;
    type: string;
    system?: string;
    packageName: string;
    packageType: string;
  };
  readonly index: {
    readonly size: number;
    get(id: string): FoundryCompendiumIndexEntry | undefined;
    values(): IterableIterator<FoundryCompendiumIndexEntry>;
  };
  getIndex(options?: { fields?: string[] }): Promise<unknown>;
  getDocument(id: string): Promise<unknown>;
  getDocuments(query?: Record<string, unknown>): Promise<unknown[]>;
  configure(settings: { locked?: boolean }): Promise<unknown>;
}

declare function fromUuid(uuid: string): Promise<FoundryDocument | null>;
declare function fromUuidSync(uuid: string): FoundryDocument | null;

interface FoundryUser {
  id: string;
  name: string;
  isGM: boolean;
  active: boolean;
  /**
   * The tokens this user targets, loosely. In Foundry a Set of token
   * placeables; narrow with FoundryTargetingUser. Loose here so the narrowed
   * declarations of packages keep extending this interface.
   */
  targets?: unknown;
  /** Replace this user's targets by these token ids on the viewed scene. */
  updateTokenTargets?(targetIds: string[]): unknown;
}

/** One target: a token placeable in Foundry, with its document. */
interface FoundryTokenTarget {
  readonly id: string;
  readonly document?: FoundryDocument;
}

/** A user whose targets are read or set. */
interface FoundryTargetingUser extends FoundryUser {
  targets: Set<FoundryTokenTarget>;
  updateTokenTargets(targetIds: string[]): unknown;
}

/** An actor, loosely: what the core knows of every system's actors. */
interface FoundryActor extends FoundryDocument {
  type?: string;
  /** An unsaved token document for this actor, from its prototype token and `data`. */
  getTokenDocument?(
    data?: Record<string, unknown>,
    options?: Record<string, unknown>
  ): Promise<FoundryDocument>;
}

interface FoundrySettingConfig {
  name?: string;
  hint?: string;
  scope: 'world' | 'client';
  config: boolean;
  type: typeof String | typeof Number | typeof Boolean;
  default: unknown;
  choices?: Record<string, string>;
  range?: { min: number; max: number; step: number };
  onChange?: (value: unknown) => void;
}

interface FoundryGame {
  ready: boolean;
  version: string;
  user: FoundryUser | null;
  users: FoundryCollection<FoundryUser> | undefined;
  /** The world collections. They exist once the world is ready (requireWorld). */
  actors: FoundryCollection<FoundryDocument>;
  cards: FoundryCollection<FoundryDocument>;
  combats: FoundryCollection<FoundryDocument>;
  folders: FoundryCollection<FoundryDocument>;
  items: FoundryCollection<FoundryDocument>;
  journal: FoundryCollection<FoundryDocument>;
  macros: FoundryCollection<FoundryDocument>;
  messages: FoundryCollection<FoundryDocument>;
  /** Every compendium, by its full id. */
  packs: FoundryCollection<FoundryCompendium>;
  playlists: FoundryCollection<FoundryDocument>;
  scenes: FoundryCollection<FoundryDocument>;
  tables: FoundryCollection<FoundryDocument>;
  world: { id: string; title: string } | undefined;
  system: { id: string; version: string } | undefined;
  /**
   * The valid subtypes per document name, e.g. `{ Actor: ['character', 'npc'] }`.
   * Present in Foundry 13 and 14; optional because a fake world may
   * leave it out, and code that checks types then leaves the check to Foundry.
   */
  documentTypes?: Record<string, string[]>;
  settings: {
    register(namespace: string, key: string, config: FoundrySettingConfig): void;
    get(namespace: string, key: string): unknown;
    set(namespace: string, key: string, value: unknown): Promise<unknown>;
  };
  i18n: {
    localize(key: string): string;
    format(key: string, data: Record<string, string>): string;
  };
  modules: {
    get(id: string): { id: string; version?: string; api?: unknown } | undefined;
  };
}

declare const game: FoundryGame;

/**
 * Foundry's CONFIG, deliberately loose. A package narrows it by merging members
 * into this interface in its own foundry.d.ts (named after the package only when
 * no other package needs them), never by declaring CONFIG again.
 */
interface FoundryConfig {
  [documentName: string]: unknown;
}

declare const CONFIG: FoundryConfig;

declare const ui: {
  notifications?: {
    info(message: string): void;
    warn(message: string): void;
    error(message: string): void;
  };
};

declare const Hooks: {
  on(name: string, callback: (...args: any[]) => unknown): number;
  once(name: string, callback: (...args: any[]) => unknown): number;
  /** Remove a hook by the id `on` returned, or by the callback itself. */
  off(name: string, idOrCallback: number | ((...args: any[]) => unknown)): void;
  callAll(name: string, ...args: unknown[]): boolean;
};
